### ISSUE TITLE
更新BIOS后还能引导吗

### ISSUE THREAD

**Issue by ccyybn** [tylinux/hackintosh-ASUS-X570-Prime-Plus-3700x#10]
我发现X570自从BIOS更新2203和2407后，本来可用的EFI引导会卡住

**Comment by ccyybn** [comment]
![image](https://user-images.githubusercontent.com/7237501/92587286-06d29100-f2ca-11ea-9e1d-00a3db947173.png)

**Comment by tylinux** [comment]
我周末升级一下试试~

**Comment by tylinux** [comment]
我刚刚更新到了 2606 版本，测试没有问题的

**Comment by ccyybn** [comment]
经过蛮力排除法，终于找到是SetupVirtualMap=true导致问题，改成false就行了，奇怪的是BIOS升级前可以用true

**Comment by ccyybn** [comment]
多谢楼主的EFI提供参考，这个问题困扰了我几个月
