### ISSUE TITLE
CPU Haulted 

### ISSUE THREAD

**Issue by MarquesCoding** [tylinux/hackintosh-ASUS-X570-Prime-Plus-3700x#3]
I tried using your files and got past the boot selector and loading verbose clearly but then it says 'CPU haulted' and then turns off my pc.

Specs:
Ryzen 9 3900x
Asus X570 Prime Pro
32GB Corsair RAM DDR4 3200MHz

**Comment by tylinux** [comment]
Can you take a picture of the verbose log?
