### ISSUE TITLE
motherboard and itself network card

### ISSUE THREAD

**Issue by WangShuoran** [tylinux/hackintosh-ASUS-X570-Prime-Plus-3700x#7]
As far as I know, asus prime x570 pro use i211 network card, do you integrate it? In Chinese network 'http://bbs.pcbeta.com/viewthread-1832376-1-1.html', it tell us upgrade network card drive. I want to know do you integrated it?
And I use Pcie 4.0 SSD, can it work?

**Comment by tylinux** [comment]
The i211 network card is supported, I have no PCIE 4.0 device, so I can't confirm if it's supported.
